# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 15:17
from __future__ import unicode_literals

import DjangoUeditor.models
import blog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('url', models.CharField(default='', max_length=100, verbose_name='文章hash')),
                ('desc', models.CharField(default='', max_length=128, verbose_name='描述')),
                ('Content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('click_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='不能小于%(limit_value)s.')], verbose_name='浏览量')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否发布')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_original', models.BooleanField(default=True, verbose_name='是否原创')),
                ('url_old', models.CharField(blank=True, max_length=100, verbose_name='原文链接')),
                ('website', models.CharField(max_length=100, verbose_name='来源站点')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='分类')),
                ('Weights', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
                ('SubClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-Weights', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='站点名')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('Weights', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否批准')),
                ('desc', models.TextField(blank=True, default='', verbose_name='站点说明')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签')),
                ('Weights', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签'),
        ),
    ]
