# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=100, verbose_name='文章hash'),
        ),
    ]
