# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180108_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文章hash'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原文链接'),
        ),
        migrations.AlterField(
            model_name='article',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='来源站点'),
        ),
    ]
